# Generated by Django 3.0.2 on 2020-01-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200107_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='input',
            new_name='test_case',
        ),
        migrations.AlterField(
            model_name='run',
            name='language',
            field=models.CharField(choices=[('java', 'Java'), ('c_cpp', 'C/C++'), ('python', 'Python3.6')], max_length=10),
        ),
    ]
